resources:

- name: ruby-buildpack-store
  type: s3
  source:
    bucket: ((s3_bucket))
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    regexp: ruby_buildpack-cached-v(.*).zip

- name: ruby-buildpack-cflinuxfs4-store
  type: s3
  source:
    bucket: ((s3_bucket))
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    regexp: ruby_buildpack-cached-cflinuxfs4-v(.*).zip

- name: binary-buildpack-store
  type: s3
  source:
    bucket: ((s3_bucket))
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    regexp: binary_buildpack-cached-v(.*).zip

- name: binary-buildpack-cflinuxfs4-store
  type: s3
  source:
    bucket: ((s3_bucket))
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    regexp: binary_buildpack-cached-cflinuxfs4-v(.*).zip

- name: java-buildpack-store
  type: s3
  source:
    bucket: ((s3_bucket))
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    regexp: java-buildpack-offline-v(.*).zip


- name: ci-scripts
  type: git
  source:
    uri: https://github.com/orange-cloudfoundry/ci-buildpack-cached.git
- name: ruby-bp-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/ruby-buildpack.git
    tag_filter: "v*"
- name: binary-bp-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/binary-buildpack.git
    tag_filter: "v*"
- name: java-bp-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: java-buildpack
    access_token: ((github-access-token))

groups:
- name: all
  jobs:
  - deploy-ruby
  - deploy-binary
  - deploy-java
- name: ruby
  jobs:
  - deploy-ruby
- name: binary
  jobs:
  - deploy-binary
- name: java
  jobs:
  - deploy-java

jobs:

- name: deploy-ruby
  serial: true
  plan:
  - in_parallel:
    - get: ci-scripts
    - get: ruby-bp-release
      trigger: true
  - task: deploy-ruby
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: ghcr.io/orange-cloudfoundry/ci-buildpack-cached, tag: latest }
      inputs:
      - name: ruby-bp-release
        path: bp-release
      - name: ci-scripts
      outputs:
      - name: bp-cached
      run:
        path: ci-scripts/scripts/go-packager.sh
        args: [ruby]
  - put: ruby-buildpack-store
    params:
      file: "bp-cached/ruby_buildpack-cached-v*.zip"
  - put: ruby-buildpack-cflinuxfs4-store
    params:
      file: "bp-cached/ruby_buildpack-cached-cflinuxfs4*.zip"

- name: deploy-binary
  serial: true
  plan:
  - in_parallel:
    - get: ci-scripts
    - get: binary-bp-release
      trigger: true
  - task: deploy-binary
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: ghcr.io/orange-cloudfoundry/ci-buildpack-cached, tag: latest }
      inputs:
      - name: binary-bp-release
        path: bp-release
      - name: ci-scripts
      outputs:
      - name: bp-cached
      run:
        path: ci-scripts/scripts/go-packager.sh
        args: [binary]
  - put: binary-buildpack-store
    params:
      file: "bp-cached/binary_buildpack-cached-v*.zip"
  - put: binary-buildpack-cflinuxfs4-store
    params:
      file: "bp-cached/binary_buildpack-cached-cflinuxfs4-*.zip"

- name: deploy-java
  serial: true
  plan:
  - in_parallel:
    - get: ci-scripts
    - get: java-bp-release
      params:
        include_source_tarball: true
        globs:
          - "s*gz"
      trigger: true
  - task: deploy-java
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: ghcr.io/orange-cloudfoundry/ci-buildpack-cached, tag: latest }
      inputs:
      - name: java-bp-release
        path: bp-release
      - name: ci-scripts
      outputs:
      - name: bp-cached
      run:
        path: ci-scripts/scripts/rake-packager.sh
        args: [java]
  - put: java-buildpack-store
    params:
      file: "bp-cached/*.zip"

