name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build, test and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      name: build and publish 'buildpack' image
      uses: docker/build-push-action@v5.1.0
      with:
        context: buildpack-image
        push: true
        tags: |          
          ghcr.io/${{github.repository}}:${{github.sha}}
          ghcr.io/${{github.repository}}:latest

